import 'highlight.js/styles/atom-one-dark.css'

import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import { generateMarkdownMetadata } from '@/utils/markdown-metadata'
import { DataProvider } from '@/hooks/use-data'

import '../globals.css'
import { CssBaseline } from '@mui/material'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const markdownMetadatas = await generateMarkdownMetadata()
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://satccet.uniriotec.br/ccet/barrasccet.css"
          media="screen"
        />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
          integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
          strategy="beforeInteractive"
        />
        <Script
          defer
          src="https://satccet.uniriotec.br/ccet/barrasccet.js"
          type="text/javascript"
          strategy="afterInteractive"
        />
      </head>
      <body className={`${inter.className}`}>
        <DataProvider markdownMetadatas={markdownMetadatas}>
          {children}
          <Toaster />
          <CssBaseline />
        </DataProvider>
      </body>
    </html>
  )
}
