import '@/globals.scss'
import 'highlight.js/styles/atom-one-dark.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import Script from 'next/script'
import { generateMarkdownMetadata } from '@/utils/markdown-metadata'
import { DataProvider } from '@/hooks/use-data'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const markdownMetadatas = await generateMarkdownMetadata()

  return (
    <html lang="en">
      <body className={`${inter.className} overflow-y-hidden bg-gray-50`}>
        <DataProvider markdownMetadatas={markdownMetadatas}>
          {children}
          <Toaster />
        </DataProvider>
        <Script src="https://www.jdoodle.com/assets/jdoodle-pym.min.js" />
      </body>
    </html>
  )
}
